### ISSUE TITLE
Preflight actions "always" run

### ISSUE THREAD

**Issue by Mark90** [nahsi/ansible-cadvisor#23]
Hi!

Thanks a lot for sharing this role to deploy cadvisor.

I've been using it in a playbook with multiple plays.
I have tagged each play so that I can selectively run a subset of them, but I noticed that even when I don't specify the play which deploys this role, the preflight tasks from this role still run because of the special `always` tag in Ansible: https://github.com/nahsi/ansible-cadvisor/blob/24989ca5d4b6c55f35b27e61c42f25cb0b8d7975/tasks/00-preflight.yml#L2

An example playbook:
```yaml
# site.yaml
- hosts: "all"
  become: true
  roles:
    - my-role
  tags:
    - my-role

- hosts: "docker"
  become: true
  roles:
    - nahsi.cadvisor
  tags:
    - cadvisor
```

Running this with `ansible-playbook site.yaml -t my-role` will also run `00-preflight.yml`.

I'm not sure if this is intentional, or that maybe I'm just mis-using the role. Just wanted to share this. Feel free to close the issue if it doesn't bother you :)

Kind regards,
Mark
